version: '2'
services:
    gsitemanager-app:
        image: gsitemanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://gsitemanager-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=gsiteManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    gsitemanager-mongodb:
        extends:
            file: mongodb.yml
            service: gsitemanager-mongodb
